management.endpoints.web.exposure.include=*
spring.application.name=time-deposit-take-home-kata-api

#H2 Database requirements
spring.datasource.url=jdbc:h2:mem:timedeposits
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
#Leaving this blank for ease of Kata - in reality this wouldn't be hosted here
spring.datasource.password=

spring.h2.console.enabled=true
logging.level.com.zaxxer=debug


ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
